repos:
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.1
  hooks:
  - id: seed-isort-config

- repo: git@github.com:sigalei/pre-commit-hooks.git
  rev: 2c6c5e016fab9d3e3a9ef346ae9d9d38f7664f3a
  hooks:
  - id: isort
  - id: yapf
  - id: pylint
  - id: pytest
