repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.1
    hooks:
    -   id: seed-isort-config

repos:
-   repo: git@github.com:sigalei/pre-commit-hooks.git
    rev: f1291418221c9e7d10f678cb07c44d7d7c3249ad
    hooks:
    -   id: isort
    -   id: yapf
    -   id: pylint
