repos:
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.1
  hooks:
  - id: seed-isort-config

- repo: git@github.com:sigalei/pre-commit-hooks.git
  rev: b347559d232702c231e3725b81e7e9714ebeaa85
  hooks:
  - id: isort
  - id: yapf
  - id: pylint
  - id: pytest
