repos:
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.27.0
    hooks:
    -   id: yapf

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
    -   id: isort
